//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid.DSS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covid.DSS.Common.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρουσιάστηκε σφάλμα κατά το χειρισμό ενός αρχείου..
        /// </summary>
        public static string FileManipulation {
            get {
                return ResourceManager.GetString("FileManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ενέργεια στη βάση δεδομένων δεν μπόρεσε να ολοκληρωθεί..
        /// </summary>
        public static string IncompleteDatabaseOperation {
            get {
                return ResourceManager.GetString("IncompleteDatabaseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρουσιάστηκε σφάλμα στη βάση δεδομένων..
        /// </summary>
        public static string InternalDatabase {
            get {
                return ResourceManager.GetString("InternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκαν στοιχεία για τα καθορισμένα φίλτρα..
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποτυχίας συναλλαγής..
        /// </summary>
        public static string TransactionFailure {
            get {
                return ResourceManager.GetString("TransactionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη αναμενόμενες τιμές..
        /// </summary>
        public static string UnexpectedValues {
            get {
                return ResourceManager.GetString("UnexpectedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρουσιάστηκε ένα άγνωστο σφάλμα..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
